<?php
/**
*  Redirect PHTML file
*
*  This file will redirect you to proper phtm file
*
*  License: Commercial
*
* @package CORE
* @subpackage CommentsViews
* @copyright Ivan Dudas, Propulsion apps, 2012
* @version  1.0.0
* @link  http://propulsionapps.com
* @since 2012 
* @
*/
    require_once(APPLICATION_PATH."/themes/core/modules/".$_SESSION["adminTheme"]["title"]."/themePaginatorPortfolio.phtml");
?>